language: scala
jdk:
- oraclejdk7
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.m2
install:
- git clone https://omnia-bamboo:$OMNIA_CI_PASSWORD@github.com/CommBank/ci.git
- ci/sbt-setup.sh
script:
- sbt -Dsbt.global.base=$TRAVIS_BUILD_DIR/ci '; test; package'
- ci/sbt-deploy.sh
after_script:
- rm -rf ci
env:
  global:
  - secure: H5O7vVl4RY7Soh1tR3jIkBnE3RZMnCae72qHnGWINSeW7hEY6sP3N8p+ETfO527cRnfWY6rjZWU9ftQDkHxbeuGf9AdNi6stEU8XpfuP1IhNCsD2lZnYuqbAc7JsD1q+gxMztI7lvaIE2X3tm5/n1ka0vgALXitTA3jlB536q50=
  - secure: DmyRmM1dXLOSF+lzBD/g+xxQfYUXRiKI6yVRmggva8+AeiAuf1p2oe2pcJBjfXU8l5QoSUK1z781Gz4Y4s2+kKIBP1LiDghAnrMy3SjS0pKGjBiBPinhkLog9UzpZ2IFuSPq3CxMgtKJ+6zsoEumdFTdafMa2bfLiEjGUswlQNQ=
